export { default as Home } from './Home'
export { default as Scan } from './Scan'
export { default as Detail } from './Detail'
export { default as Register } from './Register'
export { default as AfterRegis } from './AfterRegis'